version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5434:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
